check:
  - thoth-build
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.20.1
  build-stratergy: Source
  registry: quay.io
  registry-org: thoth-station
  registry-project: package-update-job
  registry-secret: thoth-station-thoth-pusher-secret
deploy:
  project-org: thoth-station
  project-name: thoth-application
  image-name: package-update-job
  overlay-contextpath: package-update/overlays/test/imagestreamtag.yaml
